eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8081
spring:
    application:
        name: company-service-ms
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5433/company
        username: postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
