eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8082
spring:
    application:
        name: job-service-ms
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5433/job
        username: postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
