spring:
  application:
    name: user-service-ms
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
jwt:
  secret: 76fda2e1d5b2f21d82b61b8732b85b78
  expiration: 86400000

server:
  port: 8084
